# dummy mod
#install:
#  - sudo apt-get update 
#  - sudo apt-get install -y python3 
#  - sudo apt-get install -y  ocaml-native-compilers

sudo: false

notifications:
  email:
   - felix-language@googlegroups.com 

addons:
  apt:
    packages:
      - python3
      - ocaml-native-compilers

script: 
  - make
