# dummy mod
#install:
#  - sudo apt-get update
#  - sudo apt-get install -y python3
#  - sudo apt-get install -y  ocaml-native-compilers

sudo: false

dist: trusty

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - python3
      - ocaml-native-compilers
      - gcc-5
      - g++-5

script:
  - mkdir ocaml-tmp
  - cd ocaml-tmp
  - "curl -L https://launchpad.net/~avsm/+archive/ubuntu/ocaml42+opam12/+build/7778698/+files/ocaml_4.02.3-2ppa4~precise_amd64.deb > ocaml.deb"
  - dpkg-deb -x ocaml.deb extracted
  - tree extracted # XXX
  - cd ..
  - mkdir bin
  - ln -s /usr/bin/gcc-5 bin/gcc
  - ln -s /usr/bin/g++-5 bin/g++
  - bin/gcc --version
  - bin/g++ --version
  - python3 fbuild/fbuild-light --build-cc=/usr/bin/gcc-5 --build-cxx=/usr/bin/g++-5
  - env PATH=bin:$PATH FLX_MIN_MEM=1000 make "FBUILD_PARAMS=--build-cc=/usr/bin/gcc-5 --build-cxx=/usr/bin/g++-5"

