sudo: false

dist: trusty

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - python3
      - ocaml-native-compilers
      - gcc-5
      - g++-5

script:
  - mkdir bin
  - ln -s /usr/bin/gcc-5 bin/gcc
  - ln -s /usr/bin/g++-5 bin/g++
  - bin/gcc --version
  - bin/g++ --version
  - env PATH=bin:build/release/host/bin:$PATH LD_LIBRARY_PATH=build/release/host/lib/rtl FLX_MIN_MEM=0.01 make "FBUILD_PARAMS=--build-cc=/usr/bin/gcc-5 --build-cxx=/usr/bin/g++-5"
  - tar -czvf felix-linux.tgz build/release/host build/release/share

deploy:
  provider: releases
  api_key: 6Cf5f0fMQRzTS58cpPNKeP05GJrosVqXquFRrwLzaTnoJ68V7qwacLX3SVRynW97
  file: felix-linux.tgz 
  skip_cleanup: true
  on:
    tags: true

notifications:
  email: felix-builds@googlegroups.com

