
sudo: true
dist: trusty
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - python3
    - ocaml-native-compilers
    - gcc-6
    - g++-6
before_script:
- sudo apt-get remove g++
- git config --global user.email "skaller@users.sourceforge.net"
- git config --global user.name "skaller"
- git config --global push.default simple
- git clone -q https://skaller:${GITHUB_TOKEN}@github.com/felix-lang/linuxgccbinary.git
- mkdir -p build
- cp -r linuxgccbinary/build/* build
script:
- mkdir bin
- ln -s /usr/bin/gcc-6 bin/gcc
- ln -s /usr/bin/g++-6 bin/g++
- bin/gcc --version
- bin/g++ --version
- export PATH=bin:build/release/host/bin:$PATH LD_LIBRARY_PATH=build/release/host/lib/rtl
- export FLX_SHELL_ECHO=1
- gcc --version
- g++ --version
- ## XXXFLX_MIN_MEM=100000 make "FBUILD_PARAMS=--build-cc=/usr/bin/gcc --build-cxx=/usr/bin/g++"
- make rebuild uproot
after_success:
- mkdir linuxgccbinary/build
- mkdir linuxgccbinary/build/release
- mkdir linuxgccbinary/build/release/share
- mkdir linuxgccbinary/build/release/host
- cp -r build/release/share/* linuxgccbinary/build/release/share
- cp -r build/release/host/* linuxgccbinary/build/release/host
- cd linuxgccbinary
- nm build/release/host/lib/rtl/libflx_static.a | c++filt | grep ioutil::write | grep FILE 
- git add build/release/host/*
- git add build/release/share/*
- git commit -a -m "travis rebuild"
- git push >/dev/null 2>1
before_deploy:
- cp installscript/posixinstall.sh linuxinstall.sh
- cp installscript/linuxsetup.sh .
- export FLX_VERSION=`python3 showversion.py`
- tar -czvf felix-${FLX_VERSION}-linux64-gcc51.tgz build/release/host build/release/share
  linuxinstall.sh linuxsetup.sh hello.flx INSTALL
deploy:
  provider: releases
  api_key:
    secure: n5+jnBuG3JZAoMMuBpkTtewiazORSRkQWje/yiwaT3NaU+IdfLFBnkazp5+QD7Ox7Z5auXOM1ngtJWykf5wPDjAtpKc4C82o67nvUgBJzS3+PvFNUWXCW+8rzPGJ6Xn9wiqP80XucQvmsAgfY8UCP4Hj8DswjDgVOR5utucyRj4=
  file: felix-${FLX_VERSION}-linux64-gcc51.tgz
  skip_cleanup: true
  on:
    tags: true
notifications:
  email: felix-builds@googlegroups.com
env:
  global:
    secure: l2FEMgK9dogawsN45lgOMVuUchtVyyFdgJcBeJncCnF5Mz7lIVl1qwGbgZDV6fnWcunh7snaG5o7sUg5+g9ywFc4E9CYCyx/H7Xjcr4y1wHk9RV+K3EkSWtR1DoJnayl6n4vSvP+0o+JzLqJQS65bMNMIjDdkit8CrtEnjIpSas=
