# dummy mod
#install:
#  - sudo apt-get update 
#  - sudo apt-get install -y python3 
#  - sudo apt-get install -y  ocaml-native-compilers

sudo: false
 
addons:
  apt:
  sources:
    - ubuntu-toolchain-r-test
    packages:
    - python3
    - ocaml-native-compilers
    - g++-5

script: 
  - mkdir bin
  - ln -s `which gcc-5` bin/gcc
  - ln -s `which g++-5` bin/gcc
  - env PATH=bin:$PATH make
