sudo: false

dist: trusty

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - python3
      - ocaml-native-compilers
      - gcc-5
      - g++-5

script:
  - mkdir bin
  - ln -s /usr/bin/gcc-5 bin/gcc
  - ln -s /usr/bin/g++-5 bin/g++
  - bin/gcc --version
  - bin/g++ --version
  - echo LETS CRASH GC UNDER TRAVIS: RESET FLX_MIN_MEM
  - #env PATH=bin:build/release/host/bin:$PATH LD_LIBRARY_PATH=build/release/host/lib/rtl FLX_MIN_MEM=1000 make "FBUILD_PARAMS=--build-cc=/usr/bin/gcc-5 --build-cxx=/usr/bin/g++-5"
  - env PATH=bin:build/release/host/bin:$PATH LD_LIBRARY_PATH=build/release/host/lib/rtl FLX_MIN_MEM=0.1 make "FBUILD_PARAMS=--build-cc=/usr/bin/gcc-5 --build-cxx=/usr/bin/g++-5"

notifications:
  email: felix-builds@googlegroups.com

