# dummy mod
#install:
#  - sudo apt-get update
#  - sudo apt-get install -y python3
#  - sudo apt-get install -y  ocaml-native-compilers

sudo: false

dist: trusty

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - python3
      - ocaml-native-compilers
      - gcc-5
      - g++-5

script:
  - #mkdir ocaml-tmp
  - #cd ocaml-tmp
  - #"curl -L https://launchpad.net/~avsm/+archive/ubuntu/ocaml42+opam12/+build/7778698/+files/ocaml-native-compilers_4.02.3-2ppa4~precise_amd64.deb > ocaml_native.deb"
  - #"curl -L https://launchpad.net/~avsm/+archive/ubuntu/ocaml42+opam12/+build/7778698/+files/ocaml-base_4.02.3-2ppa4~precise_amd64.deb > ocaml_base.deb"
  - #"for f in *.deb; do dpkg-deb -x $f extracted_$f; done"
  - #ls -R extracted* # XXX
  - #cd ..
  - mkdir bin
  - ln -s /usr/bin/gcc-5 bin/gcc
  - ln -s /usr/bin/g++-5 bin/g++
  - bin/gcc --version
  - bin/g++ --version
  - python3 fbuild/fbuild-light --build-cc=/usr/bin/gcc-5 --build-cxx=/usr/bin/g++-5 --host-ocamlc=ocaml-tmp/extracted_ocaml_native.deb/usr/bin/ocamlc.opt --host-ocamlopt=ocaml-tmp/extracted_ocaml_native.deb/usr/bin/ocamlopt.opt --host-ocamllex=ocaml-tmp/extracted_ocaml_native.deb/usr/bin/ocamllex.opt
  - env PATH=bin:build/release/host/bin:$PATH LD_LIBRARY_PATH=build/release/host/lib/rtl FLX_MIN_MEM=1000 make "FBUILD_PARAMS=--build-cc=/usr/bin/gcc-5 --build-cxx=/usr/bin/g++-5"

