sudo: false
dist: trusty
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - python3
    - ocaml-native-compilers
    - gcc-5
    - g++-5
before_script:
- git config --global credential.helper "store --file=git_credentials"
- echo ${GITHUB_TOKEN}  > git_credentials 2>/dev/null
- git config --global user.email "skaller@users.sourceforge.net"
- git config --global user.name "skaller"
- git config --global push.default simple
- git clone -q https://github.com/felix-lang/linuxgccbinary.git
script:
- mkdir bin
- ln -s /usr/bin/gcc-5 bin/gcc
- ln -s /usr/bin/g++-5 bin/g++
- bin/gcc --version
- bin/g++ --version
- env PATH=bin:build/release/host/bin:$PATH LD_LIBRARY_PATH=build/release/host/lib/rtl
  XXXFLX_MIN_MEM=100000 make "FBUILD_PARAMS=--build-cc=/usr/bin/gcc-5 --build-cxx=/usr/bin/g++-5"
after_success:
- mkdir linuxbinary/build
- mkdir linuxbinary/build/release
- mkdir linuxbinary/build/release/share
- mkdir linuxbinary/build/release/host
- cp -r build/release/share/* linuxgccbinary/build/release/share
- cp -r build/release/host/* linuxgccbinary/build/release/host
- cd linuxgccbinary
- git add build/release/host/*
- git add build/release/share/*
- git commit -a -m "travis rebuild"
- git push
before_deploy:
- cp installscript/posixinstall.sh linuxinstall.sh
- cp installscript/linuxsetup.sh .
- export FLX_VERSION=`python3 showversion.py`
- tar -czvf felix-${FLX_VERSION}-linux64-gcc51.tgz build/release/host build/release/share
  linuxinstall.sh linuxsetup.sh hello.flx INSTALL
deploy:
  provider: releases
  api_key:
    secure: n5+jnBuG3JZAoMMuBpkTtewiazORSRkQWje/yiwaT3NaU+IdfLFBnkazp5+QD7Ox7Z5auXOM1ngtJWykf5wPDjAtpKc4C82o67nvUgBJzS3+PvFNUWXCW+8rzPGJ6Xn9wiqP80XucQvmsAgfY8UCP4Hj8DswjDgVOR5utucyRj4=
  file: felix-${FLX_VERSION}-linux64-gcc51.tgz
  skip_cleanup: true
  on:
    tags: true
notifications:
  email: felix-builds@googlegroups.com
dd:
  secure: CpczlvUAvmOtLiBUzq9sTfWvfOeJ9ClKvTi3Mt1BM8wlYbyc4oUG7A1TQHvsf3h9hPYIArEXJiQC3yGXnE+6cUQOljNDX8ju3UvBYxR0FFVoxyvlwe+zCSAojB0rsmc6sEFKE/rDLj2vo1FHoRVYnOfl9YvIqAjlB2rKsrwg9OE=
