init:
  - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))


install:
  - call "c:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" x64
  - git clone -q https://github.com/felix-lang/win64ocaml.git
  - move win64ocaml c:\ocaml
  - set PATH=C:\Python35-x64;c:\ocaml\bin;%PATH%
  - set PWD=.
  - set PATH=build\release\host\bin;build\release\host\lib\rtl;%PATH%

platform: 
  - x64

os: Visual Studio 2015

build_script:
  - python --version
  - ocaml -version
  - nmake

