init:
  - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))


install:
  - git clone -q https://github.com/felix-lang/win64ocaml.git
  - set PATH=C:\Python33;win64ocaml\bin;%PATH%
  - call "c:\Program Files (x86)\Microsoft Visual Studio\14.0\VC\vcvarsall.bat" x64

platform: 
  - x64

os: Visual Studio 2015

build_script:
  - python --version
  - ocaml -version
  - python fbuild/fbuild-light
  - nmake

